version: '2'
volumes:
  resin-data:

services:
  homeassistant:
    build: ./homeassistant
    ports: 
      - "8123:8123"
    volumes:
      - 'resin-data:/persistent'

  mosquitto:
    build: ./mosquitto
    expose:
      - "1883"
    volumes:
      - 'resin-data:/persistent'

  zigbee2mqtt:
    build: zigbee2mqtt
    ports:
      - "8080:8080"
    volumes:
      - 'resin-data:/persistent'
    devices: 
      - '/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2251372-if00:/dev/ttyACM0'

  diyhue:
    build: diyhue
    ports:
      - "80:80"
      - "443:443"
      - "1900:1900/udp"
      - "2100:2100/udp"
      - "1982:1982/udp"
    volumes:
      - 'resin-data:/persistent'
    labels:
      io.balena.features.supervisor-api: '1'
