
FROM %%BALENA_SERVICE_NAME%%/%%BALENA_MACHINE_NAME%%-%%BALENA_SERVICE_NAME%%:stable

RUN rmdir /config
COPY run /etc/services.d/home-assistant
RUN chmod +x /etc/services.d/home-assistant/run

# Expose standard home assistant port
EXPOSE 8123
