FROM diyhue/core:dev

RUN apt-get update && apt-get install -y \
  curl jq \
  && rm -rf /var/lib/apt/lists/*

COPY entrypoint.sh /opt/hue-emulator/entrypoint.sh
RUN chmod +x /opt/hue-emulator/entrypoint.sh

RUN echo cp /opt/hue-emulator/cert.pem /opt/hue-emulator/export/cert.pem >> /opt/hue-emulator/genCert.sh

EXPOSE 80 443 1900/udp 1982/udp 2100/udp

ENTRYPOINT [ "/opt/hue-emulator/entrypoint.sh" ]
CMD [ "/usr/bin/python3", "-u", "/opt/hue-emulator/HueEmulator3.py" ]