FROM koenkk/zigbee2mqtt

ARG CONF_DIR=/app/data
RUN mkdir -p /persistent/%%BALENA_SERVICE_NAME%% && \
    rmdir ${CONF_DIR} && \
    ln -sf /persistent/%%BALENA_SERVICE_NAME%% ${CONF_DIR} 

COPY ./configuration.yaml /app/configuration.yaml

EXPOSE 8080
